using System.Net;
using System.Text.RegularExpressions;
using FluentAssertions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.DependencyInjection;
using RTUB.Core.Entities;
using Xunit;

namespace RTUB.Integration.Tests;

/// <summary>
/// Integration tests for antiforgery (CSRF) protection on the browser authentication POSTs.
/// Tokens are always read out of the real rendered page, never generated by the test.
/// </summary>
public class AuthAntiforgeryTests : IntegrationTestBase
{
    private const string IdentityCookieName = ".AspNetCore.Identity.Application";

    public AuthAntiforgeryTests(TestWebApplicationFactory factory) : base(factory)
    {
    }

    [Fact]
    public async Task LoginPage_RendersAntiforgeryToken()
    {
        var client = CreateBrowserClient();

        var response = await client.GetAsync("/login");
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        AntiforgeryFormToken.Find(await response.Content.ReadAsStringAsync())
            .Should().NotBeNullOrEmpty("the login form must render a framework antiforgery token");
    }

    [Fact]
    public async Task LoginPost_WithoutAntiforgeryToken_IsRejected()
    {
        var user = await CreateUserAsync("csrf-login-missing", "CsrfTest123!");
        var client = CreateBrowserClient();

        var response = await client.PostAsync("/auth/login", new FormUrlEncodedContent(
            new Dictionary<string, string>
            {
                ["Username"] = user.UserName!,
                ["Password"] = "CsrfTest123!",
                ["RememberMe"] = "false"
            }));

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        SetCookieHeaders(response).Should().NotContain(c => c.Contains(IdentityCookieName),
            "a rejected login must not issue a sign-in cookie");
    }

    [Fact]
    public async Task LoginPost_WithTamperedAntiforgeryToken_IsRejected()
    {
        var user = await CreateUserAsync("csrf-login-tampered", "CsrfTest123!");
        var client = CreateBrowserClient();

        // Visit the real page first so the antiforgery cookie is issued, then corrupt the token.
        var token = await ReadTokenAsync(client, "/login");

        var response = await client.PostAsync("/auth/login", new FormUrlEncodedContent(
            new Dictionary<string, string>
            {
                [AntiforgeryFormToken.FieldName] = Tamper(token),
                ["Username"] = user.UserName!,
                ["Password"] = "CsrfTest123!",
                ["RememberMe"] = "false"
            }));

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        SetCookieHeaders(response).Should().NotContain(c => c.Contains(IdentityCookieName),
            "a rejected login must not issue a sign-in cookie");
    }

    [Fact]
    public async Task LoginPost_WithTokenFromRenderedForm_SignsUserIn()
    {
        var client = CreateBrowserClient();

        var response = await LoginThroughRenderedFormAsync(client, "csrf-login-ok", "CsrfTest123!");

        response.StatusCode.Should().Be(HttpStatusCode.Redirect);
        response.Headers.Location!.ToString().Should().Be("/");
        SetCookieHeaders(response).Should().Contain(c => c.Contains(IdentityCookieName),
            "a valid login must issue the sign-in cookie");
    }

    [Fact]
    public async Task LogoutPost_WithoutAntiforgeryToken_IsRejected()
    {
        var client = CreateBrowserClient();

        var response = await client.PostAsync("/auth/logout", TokenlessLogoutForm());

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    [Fact]
    public async Task LogoutPost_WhileAuthenticated_WithoutAntiforgeryToken_KeepsSessionSignedIn()
    {
        var client = CreateBrowserClient();
        await LoginThroughRenderedFormAsync(client, "csrf-logout-missing", "CsrfTest123!");

        var response = await client.PostAsync("/auth/logout", TokenlessLogoutForm());

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);

        // The logout form only renders for an authenticated user, so its presence proves
        // the rejected request did not sign the session out.
        var page = await client.GetStringAsync("/");
        page.Should().Contain("/auth/logout", "a rejected logout must leave the session signed in");
    }

    [Fact]
    public async Task LogoutPost_WithTokenFromRenderedForm_SignsUserOut()
    {
        var client = CreateBrowserClient();
        await LoginThroughRenderedFormAsync(client, "csrf-logout-ok", "CsrfTest123!");

        // The logout form lives in MainLayout, so any authenticated page renders its token.
        var token = await ReadTokenAsync(client, "/");

        var response = await client.PostAsync("/auth/logout", new FormUrlEncodedContent(
            new Dictionary<string, string> { [AntiforgeryFormToken.FieldName] = token }));

        response.StatusCode.Should().Be(HttpStatusCode.Redirect);
        response.Headers.Location!.ToString().Should().Be("/");
        SetCookieHeaders(response).Should().Contain(
            c => c.StartsWith(IdentityCookieName + "=;", StringComparison.Ordinal),
            "a valid logout must clear the sign-in cookie");
    }

    private HttpClient CreateBrowserClient() => Factory.CreateClient(new WebApplicationFactoryClientOptions
    {
        AllowAutoRedirect = false,
        HandleCookies = true
    });

    private async Task<ApplicationUser> CreateUserAsync(string userName, string password)
    {
        using var scope = Factory.Services.CreateScope();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var user = new ApplicationUser
        {
            UserName = userName,
            Email = $"{userName}@test.com",
            EmailConfirmed = true,
            FirstName = "Anti",
            LastName = "Forgery",
            Nickname = userName,
            PhoneNumber = "123456789"
        };

        var result = await userManager.CreateAsync(user, password);
        result.Succeeded.Should().BeTrue();
        return user;
    }

    /// <summary>
    /// Drives the real browser flow: GET the login page, read its antiforgery token, POST the form.
    /// </summary>
    private async Task<HttpResponseMessage> LoginThroughRenderedFormAsync(
        HttpClient client, string userName, string password)
    {
        var user = await CreateUserAsync(userName, password);
        var token = await ReadTokenAsync(client, "/login");

        return await client.PostAsync("/auth/login", new FormUrlEncodedContent(
            new Dictionary<string, string>
            {
                [AntiforgeryFormToken.FieldName] = token,
                ["Username"] = user.UserName!,
                ["Password"] = password,
                ["RememberMe"] = "false"
            }));
    }

    private static async Task<string> ReadTokenAsync(HttpClient client, string path)
    {
        var response = await client.GetAsync(path);
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        var token = AntiforgeryFormToken.Find(await response.Content.ReadAsStringAsync());
        token.Should().NotBeNullOrEmpty($"{path} must render a framework antiforgery token");
        return token!;
    }

    /// <summary>
    /// A logout POST body with no antiforgery token. The body is deliberately non-empty: an empty
    /// one is rejected with 400 because the request has no body at all, which would make an
    /// antiforgery test pass for the wrong reason.
    /// </summary>
    private static FormUrlEncodedContent TokenlessLogoutForm() => new(
        new Dictionary<string, string> { ["_handler"] = "LogoutForm" });

    private static IEnumerable<string> SetCookieHeaders(HttpResponseMessage response) =>
        response.Headers.TryGetValues("Set-Cookie", out var values) ? values : Array.Empty<string>();

    private static string Tamper(string token) =>
        token[..^1] + (token[^1] == 'A' ? 'B' : 'A');
}

/// <summary>
/// Reads the antiforgery hidden field out of rendered HTML, the same way a browser would.
/// </summary>
internal static partial class AntiforgeryFormToken
{
    /// <summary>Default <c>AntiforgeryOptions.FormFieldName</c>; the app does not override it.</summary>
    internal const string FieldName = "__RequestVerificationToken";

    internal static string? Find(string html)
    {
        var match = TokenInput().Match(html);
        return match.Success ? match.Groups["value"].Value : null;
    }

    [GeneratedRegex(
        "<input[^>]*\\bname=\"" + FieldName + "\"[^>]*\\bvalue=\"(?<value>[^\"]+)\"",
        RegexOptions.IgnoreCase)]
    private static partial Regex TokenInput();
}
