// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RTUB.Application.Data;

#nullable disable

namespace RTUB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107030000_RestoreMissingEnrollmentColumns")]
    partial class RestoreMissingEnrollmentColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
#pragma warning restore 612, 618
        }
    }
}
