// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RTUB.Application.Data;

#nullable disable

namespace RTUB.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260202123000_AddEnemiesDefeatedToStageProgress")]
partial class AddEnemiesDefeatedToStageProgress
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles", (string)null);
            });

        // (Omitting other entities for brevity - they remain unchanged)
        // The full model would include all entities from ApplicationDbContextModelSnapshot.cs

        modelBuilder.Entity("RTUB.Core.Entities.StageProgress", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<int>("CurrentRegion")
                    .HasColumnType("INTEGER");

                b.Property<int>("CurrentStage")
                    .HasColumnType("INTEGER");

                b.Property<int>("EnemiesDefeatedInCurrentStage")
                    .HasColumnType("INTEGER");

                b.Property<bool>("EndlessModeUnlocked")
                    .HasColumnType("INTEGER");

                b.Property<int>("HighestStage")
                    .HasColumnType("INTEGER");

                b.Property<int>("LastCheckpoint")
                    .HasColumnType("INTEGER");

                b.Property<int>("TotalBossesDefeated")
                    .HasColumnType("INTEGER");

                b.Property<int>("TotalMiniBossesDefeated")
                    .HasColumnType("INTEGER");

                b.Property<int>("TotalStagesCleared")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("HighestStage")
                    .HasDatabaseName("IX_StageProgresses_HighestStage");

                b.HasIndex("UserId")
                    .IsUnique()
                    .HasDatabaseName("IX_StageProgresses_UserId");

                b.ToTable("StageProgresses");
            });

#pragma warning restore 612, 618
    }
}
