// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RTUB.Application.Data;

#nullable disable

namespace RTUB.Web.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260204_AddBattlePendingRewardsFields")]
partial class AddBattlePendingRewardsFields
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0");

        // Battle entity
        modelBuilder.Entity("RTUB.Core.Entities.Battle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("AttackerCharacterId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("AttackerFidelis")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<int?>("AttackerFinalHP")
                    .HasColumnType("INTEGER");

                b.Property<int>("AttackerXP")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<int>("DefenderCharacterId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("DefenderFidelis")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<int>("DefenderXP")
                    .HasColumnType("INTEGER");

                b.Property<int>("Outcome")
                    .HasColumnType("INTEGER");

                b.Property<string>("ReplayJson")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("RewardsApplied")
                    .HasColumnType("INTEGER");

                b.Property<int>("Seed")
                    .HasColumnType("INTEGER");

                b.Property<bool>("ShotBuffExpired")
                    .HasColumnType("INTEGER");

                b.Property<bool>("ShotBuffUsed")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AttackerCharacterId")
                    .HasDatabaseName("IX_Battles_AttackerCharacterId");

                b.HasIndex("CreatedAt")
                    .HasDatabaseName("IX_Battles_CreatedAt");

                b.HasIndex("DefenderCharacterId")
                    .HasDatabaseName("IX_Battles_DefenderCharacterId");

                b.ToTable("Battles");
            });
#pragma warning restore 612, 618
    }
}
