// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RTUB.Application.Data;

#nullable disable

namespace RTUB.Web.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260205095749_RemoveBattleAndStageBattleTables")]
partial class RemoveBattleAndStageBattleTables
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles", (string)null);
            });

        modelBuilder.Entity("RTUB.Core.Entities.Character", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ArenaDraws")
                    .HasColumnType("INTEGER");

                b.Property<int>("ArenaLosses")
                    .HasColumnType("INTEGER");

                b.Property<int>("ArenaWins")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<double>("CriticalChance")
                    .HasColumnType("REAL");

                b.Property<int>("CriticalUpgrades")
                    .HasColumnType("INTEGER");

                b.Property<int?>("CurrentHP")
                    .HasColumnType("INTEGER");

                b.Property<int>("Defense")
                    .HasColumnType("INTEGER");

                b.Property<int>("DefenseUpgrades")
                    .HasColumnType("INTEGER");

                b.Property<int>("HP")
                    .HasColumnType("INTEGER");

                b.Property<int>("HpUpgrades")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("LastBattleAt")
                    .HasColumnType("TEXT");

                b.Property<int?>("LastOpponentId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Level")
                    .HasColumnType("INTEGER");

                b.Property<int>("Power")
                    .HasColumnType("INTEGER");

                b.Property<int>("PowerUpgrades")
                    .HasColumnType("INTEGER");

                b.Property<int>("ShotBuffBattlesRemaining")
                    .HasColumnType("INTEGER");

                b.Property<int>("Speed")
                    .HasColumnType("INTEGER");

                b.Property<int>("SpeedUpgrades")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("TEXT");

                b.Property<int>("XP")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Level")
                    .HasDatabaseName("IX_Characters_Level");

                b.HasIndex("UserId")
                    .IsUnique()
                    .HasDatabaseName("IX_Characters_UserId");

                b.ToTable("Characters");
            });

        modelBuilder.Entity("RTUB.Core.Entities.StageEnemy", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<double>("BaseCriticalChance")
                    .HasColumnType("REAL");

                b.Property<int>("BaseDefense")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("BaseFidelisDrop")
                    .HasPrecision(18, 2)
                    .HasColumnType("TEXT");

                b.Property<int>("BaseHP")
                    .HasColumnType("INTEGER");

                b.Property<int>("BasePower")
                    .HasColumnType("INTEGER");

                b.Property<int>("BaseSpeed")
                    .HasColumnType("INTEGER");

                b.Property<double>("BeerDropChance")
                    .HasColumnType("REAL");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int>("Region")
                    .HasColumnType("INTEGER");

                b.Property<double>("ShotDropChance")
                    .HasColumnType("REAL");

                b.Property<string>("SpritePath")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("Type")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Region")
                    .HasDatabaseName("IX_StageEnemies_Region");

                b.HasIndex("Type")
                    .HasDatabaseName("IX_StageEnemies_Type");

                b.HasIndex("Type", "Region")
                    .HasDatabaseName("IX_StageEnemies_Type_Region");

                b.ToTable("StageEnemies");
            });

        modelBuilder.Entity("RTUB.Core.Entities.StageProgress", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<int>("CurrentRegion")
                    .HasColumnType("INTEGER");

                b.Property<int>("CurrentStage")
                    .HasColumnType("INTEGER");

                b.Property<bool>("EndlessModeUnlocked")
                    .HasColumnType("INTEGER");

                b.Property<int>("EnemiesDefeatedInCurrentStage")
                    .HasColumnType("INTEGER");

                b.Property<int>("HighestStage")
                    .HasColumnType("INTEGER");

                b.Property<int>("LastCheckpoint")
                    .HasColumnType("INTEGER");

                b.Property<int>("TotalBossesDefeated")
                    .HasColumnType("INTEGER");

                b.Property<int>("TotalMiniBossesDefeated")
                    .HasColumnType("INTEGER");

                b.Property<int>("TotalStagesCleared")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("HighestStage")
                    .HasDatabaseName("IX_StageProgresses_HighestStage");

                b.HasIndex("UserId")
                    .IsUnique()
                    .HasDatabaseName("IX_StageProgresses_UserId");

                b.ToTable("StageProgresses");
            });

        modelBuilder.Entity("RTUB.Core.Entities.Character", b =>
            {
                b.HasOne("RTUB.Core.Entities.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("RTUB.Core.Entities.StageProgress", b =>
            {
                b.HasOne("RTUB.Core.Entities.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

#pragma warning restore 612, 618
    }
}
